# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install sshpass
      run: sudo apt-get install sshpass
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.7'
        mysql database: 'mock_hotel'
        mysql user: 'work'
        mysql password: 'password'
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping --host=127.0.0.1 --password='root' --silent; do
          sleep 1
        done
    - name: Test with pytest
      run: |
        pytest
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: bash run.sh
